In [2]:
import numpy as np

In [14]:
# create 500 x 1 array
exp_indices = np.arange(500)
cv_splits = np.array_split(exp_indices, 5)
cv_splits[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
# reshape cv_splits[0] into 5 x 20 array
cv_splits_reshape = np.array(cv_splits[0]).reshape(5, 20)
print(cv_splits_reshape)
print(cv_splits_reshape.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
(5, 20)


In [18]:
cv_splits_reshape = np.reshape(cv_splits_reshape, cv_splits_reshape.shape[0] \
           * cv_splits_reshape.shape[1])
print(cv_splits_reshape)
print(cv_splits_reshape.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [21]:
cv_splits_reshape = np.reshape(cv_splits_reshape, (5, 20))
print(cv_splits_reshape)
print(cv_splits_reshape.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
(5, 20)


In [30]:
vector = np.arange(100)
print(vector)
# array is 2d, with rows 5:10, 15:20, 25:30, 35:40, 45:50
array = np.reshape(vector, (10, 10))
array = array[0:5, 5:10]
print(array)
print(array.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]
(5, 5)


In [35]:
array2 = vector[..., array]
print(array2)
print(array2.shape)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]
(5, 5)


In [31]:
array2 = vector[array]
print(array2)
print(array2.shape)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]
(5, 5)


In [39]:
vector2 = vector + 100
print(vector2)

# make an array that has vector and vector2 as columns
array3 = np.column_stack((vector, vector2))
print(array3)
print(array3.shape)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
[[  0 100]
 [  1 101]
 [  2 102]
 [  3 103]
 [  4 104]
 [  5 105]
 [  6 106]
 [  7 107]
 [  8 108]
 [  9 109]
 [ 10 110]
 [ 11 111]
 [ 12 112]
 [ 13 113]
 [ 14 114]
 [ 15 115]
 [ 16 116]
 [ 17 117]
 [ 18 118]
 [ 19 119]
 [ 20 120]
 [ 21 121]
 [ 22 122]
 [ 23 123]
 [ 24 124]
 [ 25 125]
 [ 26 126]
 [ 27 127]
 [ 28 128]
 [ 29 129]
 [ 30 130]
 [ 31 131]
 [ 32 132]
 [ 33 133]
 [ 34 134]
 [ 35 135]
 [ 36 136]
 [ 37 137]
 [ 38 138]
 [ 39 139]
 [ 40 140]
 [ 41 141]
 [ 42 142]
 [ 43 143]
 [ 44 144]
 [ 45 145]
 [ 46 146]
 [ 47 147]
 [ 48 148]
 [ 49 149]
 [ 50 150]
 [ 51 151]
 [ 52 152]
 [ 53 153]

In [45]:
array4 = array3[array, ...]
print(array4[1,:,:])
print(array4[2,:,:])
print(array4.shape)

[[ 15 115]
 [ 16 116]
 [ 17 117]
 [ 18 118]
 [ 19 119]]
[[ 25 125]
 [ 26 126]
 [ 27 127]
 [ 28 128]
 [ 29 129]]
(5, 5, 2)


In [47]:
len(array3.shape)

2

In [50]:
np.arange(0, 64 + 1, 16)[1::] - 1

array([15, 31, 47, 63])

In [51]:
array4.shape

(5, 5, 2)

In [53]:
array5 = array4[:, [1,2,3]]
print(array5)
print(array5.shape)

[[[  6 106]
  [  7 107]
  [  8 108]]

 [[ 16 116]
  [ 17 117]
  [ 18 118]]

 [[ 26 126]
  [ 27 127]
  [ 28 128]]

 [[ 36 136]
  [ 37 137]
  [ 38 138]]

 [[ 46 146]
  [ 47 147]
  [ 48 148]]]
(5, 3, 2)
